### ISSUE TITLE
Finalizace programování - checklist

### ISSUE THREAD

**Issue by Tasssadar** [RoboticsBrno/robotka.robotickytabor.cz#6]
- [ ] Souhlasí s příklady na gitu
- [ ] Sedí čísla řádků
- [ ] Odkazy fungují
- [ ] ID motorů v rk 
- [ ] Piny v rk
